pipeline{
    agent{
        docker{
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages{
         stage('Checkout') {
      steps {
        sh 'echo passed'
        
      }
        stage('Build And Install'){
            steps{
                sh 'cd helloworld && mvn clean install'
            }
        }
