pipeline{
    agent{
        docker{
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages{
         stage('Checkout') {
      steps {
        sh 'echo passed'
        
      }
         }    
        stage('Build And Install'){
            steps{
                sh 'cd helloworld && mvn clean package'
            }
        }
        stage('Static Code Analysis'){
            environment{
            SONAR_URL="http://65.0.131.171:9000"
            }
            steps{
              withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]){
                sh 'cd helloworld && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'                  
              }
            }  
        }

            
  }
}      
