pipeline{
    agent{
        docker{
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages{
         stage('Checkout') {
      steps {
        sh 'echo passed'
        
      }
         }    
        stage('Build And Install'){
            steps{
                sh 'cd helloworld && mvn clean package'
            }
        }
        stage('Static Code Analysis'){
            environment{
            SONAR_URL = "http://65.0.131.171:9000"
            }
            steps{
              withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]){
                sh 'cd helloworld && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'                  
              }
            }  
        }
        stage('Docker Image Push'){
            environment{
               DOCKER_IMAGE= "bijjampoorna/helloworld:${BUILD_NUMBER}"
               REGISTRY_CREDENTIALS= credentials('docker-cred') 
            }
            steps{
                script{
                    sh 'cd helloworld && docker build -t ${DOCKER_IMAGE} . '
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                     docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                             dockerImage.push()
                    }
                }
            }
        }
        stage('Deploying Image'){
            environment{
                GIT_REPO_NAME="helloworld"
                GIT_USER_NAME="Bijjampoorna"
            }
            steps{
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]){
                    sh '''
                        git config user.email "bijjampoorna@gmail.com"
                        got config user.name "Bijjampoorna"
                      
                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" helloworld_manifest/deployment.yml
                        git add helloworld_manifest/deployment.yml
                        git commit -m "update deployment with $BUILD_NUMBER"
                        git push https://$GITHUB_TOKEN@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
                    '''
                }
            }
        }

            
  }
}      
